# Imports

In [1]:
import torch
import torchvision
import torchvision.transforms as transforms
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt

import numpy as np
import pandas as pd

/home/aditya/miniconda3/envs/QCNet/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/aditya/miniconda3/envs/QCNet/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(


# 0. TENSORS
___________

Torch tensors are the core data structure in PyTorch, similar to NumPy arrays but optimized for deep learning. They support GPU acceleration, automatic differentiation for neural network training, and can easily interact with NumPy.
____________

### 0.1 Making Tesnors 

In [2]:
import torch

# 1. Tensor of integers
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)

# 2. Tensor of floating-point numbers
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)

# 3. Random tensor of shape (2, 3) with values from a normal distribution
random_tensor = torch.randn(2, 3)

In [3]:
int_tensor.ndim

1

In [4]:
float_tensor

tensor([1., 2., 3.])

In [5]:
random_tensor.shape

torch.Size([2, 3])

In [6]:
random_tensor.shape

torch.Size([2, 3])

### 0.2 Tensor Operations

In [7]:
a = torch.tensor([10.0, 20.0])
b = torch.tensor([50.0, 200.0])

In [8]:
# Addition (& Substraction)
a+b         

tensor([ 60., 220.])

In [9]:
# Multiplication
a*b

tensor([ 500., 4000.])

In [10]:
# Division
a/b

tensor([0.2000, 0.1000])

In [11]:
# Matrix Multiplication
A = torch.rand(2,3)
B = torch.randn(3,5)

print('A :', end=' ')
print(A)

print()

print('B :', end=' ')
print(B)

A : tensor([[0.3456, 0.3204, 0.8168],
        [0.3805, 0.5172, 0.9331]])

B : tensor([[-1.3031,  1.0857,  0.2267,  0.1108,  1.1635],
        [ 0.6490, -0.0245, -1.0199, -2.2657,  1.4541],
        [-2.8988, -0.0543, -0.4541,  0.5760,  0.5210]])


In [12]:
# Matrix Multiplication
torch.matmul(A,B)

tensor([[-2.6100,  0.3230, -0.6193, -0.2171,  1.2934],
        [-2.8651,  0.3498, -0.8649, -0.5921,  1.6809]])

In [13]:
# Matrix Multiplication
A@B

tensor([[-2.6100,  0.3230, -0.6193, -0.2171,  1.2934],
        [-2.8651,  0.3498, -0.8649, -0.5921,  1.6809]])

### 0.3 Tensor Attributes

Tensor attributes provide essential metadata about a tensor, such as its shape, data type, and location in memory. They describe the structure, content, and computational context of the tensor, enabling you to manage and manipulate it effectively in PyTorch operations. Some o them are listed below

##### 1. shape: Dimensions of the tensor.
##### 2. dtype: Data type of the tensor's elements.
##### 3. device: Indicates CPU or GPU location.
##### 4. requires_grad: Tracks gradients for optimization.
##### 5. ndim: Number of dimensions in the tensor.


In [14]:
tensor = torch.randn(4,3)

In [15]:
tensor.shape

torch.Size([4, 3])

In [16]:
tensor.dtype

torch.float32

In [17]:
tensor.device

device(type='cpu')

In [18]:
tensor.requires_grad

False

In [19]:
tensor.ndim

2

__________________________________
# THANK YOU
________________________